### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by llambda** [webpack/css-loader#141]
Just updated to latest webpack and css-loader

```
ERROR in ../~/css-loader!./style.css
Module build failed: TypeError: Cannot read property 'length' of undefined
    at walk (/app/node_modules/postcss-value-parser/lib/index.js:27:28)
    at ValueParser.walk (/app/node_modules/postcss-value-parser/lib/index.js:19:5)
    at /app/node_modules/postcss-convert-values/dist/index.js:27:71
    at /app/node_modules/postcss/lib/container.js:88:34
    at /app/node_modules/postcss/lib/container.js:73:26
    at Rule.each (/app/node_modules/postcss/lib/container.js:59:22)
    at Rule.walk (/app/node_modules/postcss/lib/container.js:72:21)
    at /app/node_modules/postcss/lib/container.js:76:32
    at Root.each (/app/node_modules/postcss/lib/container.js:59:22)
    at Root.walk (/app/node_modules/postcss/lib/container.js:72:21)
    at Root.walkDecls (/app/node_modules/postcss/lib/container.js:86:25)
    at /app/node_modules/postcss-convert-values/dist/index.js:58:13
    at LazyResult.run (/app/node_modules/postcss/lib/lazy-result.js:201:20)
    at /app/node_modules/postcss/lib/lazy-result.js:115:37
    at LazyResult.asyncTick (/app/node_modules/postcss/lib/lazy-result.js:129:15)
    at /app/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/app/node_modules/postcss/lib/lazy-result.js:129:15)
    at /app/node_modules/postcss/lib/lazy-result.js:120:31
    at process._tickCallback (node.js:356:9)
 @ ./style.css 4:14-72
```

**Comment by ben-eb** [comment]
What's the CSS that generates this error?

**Comment by llambda** [comment]
Oops,,, I somehow had

```
*::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px #06ab6e);
    -webkit-border-radius: 10px;
    border-radius: 10px;
}
*::-webkit-scrollbar-thumb {
    -webkit-border-radius: 10px;
    border-radius: 10px;
    background: #06ab6e;
    -webkit-box-shadow: inset 0 0 6px #06ab6e);
}
```

Removing the extraneous ')' fixed the problem.

**Comment by ben-eb** [comment]
:+1:

**Comment by biplabmalakar** [comment]
Hi facing the same issue. ng serve was showing an error of environmentSource entry missing. I maintained the entry and proceeded again with the same command and now the build failed with the error - 

![image](https://cloud.githubusercontent.com/assets/25076695/25004238/2d0d0050-2008-11e7-9713-305055737d63.png)

Any help with this is highly appreciated.
Thank you
