### ISSUE TITLE
css-loader don't load a file

### ISSUE THREAD

**Issue by franckmaurin** [webpack/css-loader#165]
Hello,

I've a strange bug when I compile with webpack my react project (using css-loader):
```
ERROR in ./~/css-loader!./~/cssnext-loader!./src/components/Work/Single/Nav/styles.css
TypeError: Cannot read property 'map' of undefined

ERROR in ./~/css-loader!./~/cssnext-loader!./src/components/Work/Single/Nav/styles.css
Module build failed: TypeError: Cannot read property 'toString' of undefined
    at new Input (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/input.js:31:23)
    at parse (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/parse.js:21:17)
    at new LazyResult (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:57:24)
    at Processor.process (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/processor.js:36:16)
    at processCss (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/lib/processCss.js:165:11)
    at Object.module.exports (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/lib/loader.js:22:2)
 @ ./src/components/Work/Single/Nav/styles.css 4:14-143

ERROR in ./src/components/Work/Single/Nav/styles.css
Module build failed: ModuleError: TypeError: Cannot read property 'map' of undefined
    at DependenciesBlock.<anonymous> (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:79:21)
    at Object.cssnextLoader (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/cssnext-loader/index.js:36:10)
```

If I console.log the content in the /css-loader/lib/loader.js, I get "undefined" for one css file (Work/Single/Nav/styles.css).

The css file in question has this following code :
```
.workSingle-nav {
  border-top: solid 3px #fff;
  padding: 20px 0;
}
.workSingle-nav-item {
  display: inline-block;
  margin-right: 20px;
}
.workSingle-nav-item a {
  display: inline-block;
  text-decoration: none;
  font-size: 13px;
  text-transform: uppercase;
  letter-spacing: 1px;
  font-weight: 600;
  color: #fff;
}
```
The most surprising is that if I remove the line 10 "display: inline-block" , the bug disappear.

Have u any idea of this ? Thanks.

**Comment by franckmaurin** [comment]
ok that's finally fixed by a new release of cssnano.
https://github.com/postcss/postcss/issues/600
