### ISSUE TITLE
:global and :local property values? Animation-name is crashing the pipeline instead of being converted

### ISSUE THREAD

**Issue by Jabher** [webpack/css-loader#166]
**css-loader** is crashing on this code: 

```
@keyframes :local(blink){...}
.style {animation-name: :local(blink);} 
```

Crash is caused by `animation-name: :local(blink)`.
I'm not quite sure it is wrong behavior but in case keyframes gets localised, then animation names should be localized also, right?
An error I'm getting in pipeline:

```

ERROR in ./~/css-loader?localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./src/react/components/smart/Root.css
Module build failed: Error: "/Users/jabher/qtopia/Root.css" is not in the SourceMap.
    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (/Users/jabher/qtopia/node_modules/css-loader/node_modules/postcss/node_modules/source-map/lib/source-map-consumer.js:703:15)
    at Input.origin (/Users/jabher/qtopia/node_modules/css-loader/node_modules/postcss/lib/input.js:83:31)
    at Input.error (/Users/jabher/qtopia/node_modules/css-loader/node_modules/postcss/lib/input.js:57:27)
    at Parser.doubleColon (/Users/jabher/qtopia/node_modules/css-loader/node_modules/postcss/lib/parser.js:492:26)
    at Parser.colon (/Users/jabher/qtopia/node_modules/css-loader/node_modules/postcss/lib/parser.js:453:26)
    at Parser.checkMissedSemicolon (/Users/jabher/qtopia/node_modules/css-loader/node_modules/postcss/lib/parser.js:505:26)
    at Parser.decl (/Users/jabher/qtopia/node_modules/css-loader/node_modules/postcss/lib/parser.js:272:50)
    at Parser.word (/Users/jabher/qtopia/node_modules/css-loader/node_modules/postcss/lib/parser.js:135:30)
    at Parser.loop (/Users/jabher/qtopia/node_modules/css-loader/node_modules/postcss/lib/parser.js:60:26)
    at parse (/Users/jabher/qtopia/node_modules/css-loader/node_modules/postcss/lib/parse.js:25:12)
    at new LazyResult (/Users/jabher/qtopia/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:57:24)
    at Processor.process (/Users/jabher/qtopia/node_modules/css-loader/node_modules/postcss/lib/processor.js:36:16)
    at processCss (/Users/jabher/qtopia/node_modules/css-loader/lib/processCss.js:166:11)
    at Object.module.exports (/Users/jabher/qtopia/node_modules/css-loader/lib/loader.js:22:2)
 @ ./src/react/components/smart/Root.css 4:14-184 13:2-17:4 14:20-190
```

**Comment by sokra** [comment]
Try this instead:

``` css
@keyframes :local(blink){...}
.style :local {animation-name: blink;} 
```

**Comment by goldensunliu** [comment]
@sokra  interesting syntax. any reason why?
