### ISSUE TITLE
Babel cannot transform 

### ISSUE THREAD

**Issue by willin** [webpack/css-loader#271]
```
babel app.js -o app.out.js
```

```
Error: Cannot find module 'css!./style.css'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/willin/Documents/wulian/v3/bash/dev/app/modules/App.js:15:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

```js
import React from 'react';
import NavLink from './NavLink';
require('css!./style.css');  // <-- Error Here
export default React.createClass({
  render() {
    return (
      <div>
        <h1>React Router Tutorial</h1>
        <ul role="nav">
          <li><NavLink to="/" onlyActiveOnIndex>Home</NavLink></li>
          <li><NavLink to="/about">About</NavLink></li>
          <li><NavLink to="/repos">Repos</NavLink></li>
        </ul>
        {this.props.children}
      </div>
    );
  }
});
```

**Comment by bebraw** [comment]
The problem is that Babel has no knowledge of webpack loaders by default. That's why it fails there.

You could try using something like [babel-plugin-webpack-loaders](https://github.com/istarkov/babel-plugin-webpack-loaders) to work around the restriction.

A good alternative could be to push the import outside of your JavaScript code and into an entry of its own. You can then generate a separate CSS bundle out of that through `ExtractTextPlugin`.
