### ISSUE TITLE
Error on carriage return in CSS stylesheet

### ISSUE THREAD

**Issue by thecuriousnoob** [webpack/css-loader#332]
Hello I've met an error using webpack bundling tool with CSS loaders like Style and CSS.

The CSS stylesheets begins with these lines.

```
html,
body {
  //some css properties
}
```

which throws the following error during build : 

```
ERROR in ./~/todomvc-app-css/index.css
Module parse failed: /Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/todomvc-app-css/index.css Unexpected token (2:5)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:5)
    at Parser.pp$4.raise (/Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseTopLevel (/Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/webpack/lib/NormalModule.js:104:16)
 @ ./src/index.jsx 19:0-52
```

**Comment by dnuske** [comment]
same here, where you able to solve it @thecuriousnoob ?

**Comment by thecuriousnoob** [comment]
@dnuske Well I just avoided CR...

**Comment by dnuske** [comment]
@thecuriousnoob I've found a solution, turns out that standard css files can be loaded with configuration 
```
{
      test: /\.csss$/,
      loaders: ['style', 'css'],
}
```
`style` and `css` come included with either css-loader or webpack already.

**Comment by thecuriousnoob** [comment]
Good job ! We may close this issue then :)
