### ISSUE TITLE
Getting optimisation issue with some CSS

### ISSUE THREAD

**Issue by MoOx** [webpack/css-loader#36]
When I use `webpack -p`, I'm getting a non helping error message

```
ERROR in ./~/css-loader!./~/cssnext-loader!./src/index.css
Module build failed: Error: Please check the validity of the CSS block starting from the line #1
    at throwError (/.../node_modules/css-loader/node_modules/csso/lib/gonzales.cssp.node.js:399:15)
    at checkStylesheet (/.../node_modules/css-loader/node_modules/csso/lib/gonzales.cssp.node.js:1921:22)
    at Object.CSSPRules.stylesheet (/.../node_modules/css-loader/node_modules/csso/lib/gonzales.cssp.node.js:365:40)
    at _getAST (/.../node_modules/css-loader/node_modules/csso/lib/gonzales.cssp.node.js:409:38)
    at exports.srcToCSSP (/.../node_modules/css-loader/node_modules/csso/lib/gonzales.cssp.node.js:2287:16)
    at Object.exports.srcToCSSP (/.../node_modules/css-loader/node_modules/csso/lib/gonzales.cssp.node.js:2292:16)
    at Object.exports.parse (/.../node_modules/css-loader/node_modules/csso/lib/cssoapi.js:7:21)
    at Object.module.exports (/.../node_modules/css-loader/index.js:18:18)
 @ ./src/index.css 4:14-293
```

In this index.css I just have some inlined `@import`, so this error is not really helping.
Is there any way to improve that?

My first import is normalize.css and after taking a look in the `<style>` element I saw some empty `:root` elements (due to the fact I use future proof CSS transformed via cssnext).
It seems the parser you are using is kind of outdated for some part.

If you are using csso for minification, would you consider switch to a more fresh tool (csswring) based on an parser with an active development (postcss)?

**Comment by jhnns** [comment]
PostCSS is backed by Autoprefixer, so it's probably developed more actively. :+1:

**Comment by MoOx** [comment]
postcss 4 is really fast (just run this to check it out https://github.com/postcss/postcss/tree/master/benchmark ) & even support CSS specs that are not implemented in browsers. So seems a really good choice indeed.

**Comment by sokra** [comment]
Yes, write a PR... I've already tried to use an alternative library in the `rework` branch.
Check that all test pass and maybe add some for the new stuff.

The `rework` branch doesn't work out, because it removed the whitespace from css and this would break SourceMap.

**Comment by MoOx** [comment]
rework is kind of unmaintained (last commit is from august 2014).
More & more people are switching to postcss now that the ecosystem start to be consistent.

**Comment by sokra** [comment]
yeah... I'm fine if you do a PR with postcss.

**Comment by MoOx** [comment]
Closing since you now use postcss
