### ISSUE TITLE
Unable to parse , rgba(255, 255, 255, .15) 25%, correctly

### ISSUE THREAD

**Issue by JEBoothjr** [webpack/css-loader#83]
ERROR in ./~/css-loader!./client/css/bootstrap.css
Module build failed: Error: Unable to parse color from string "rgba(255, 255, 255, .15 25%)"

It seems to be parsing the following line (and others like it) incorrectly:

background-image:         linear-gradient(45deg, rgba(255, 255, 255, .15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, .15) 50%, rgba(255, 255, 255, .15) 75%, transparent 75%, transparent);

This works in 0.14.5 but breaks in 0.15.0

**Comment by AlexKVal** [comment]
[react-bootstrap](https://github.com/react-bootstrap/react-bootstrap)
Same error.
```
ModuleBuildError: Module build failed: Error: Unable to parse color from string "rgba(255,255,255,0.15 25%)"
```

**Comment by jlchereau** [comment]
Same thing here: build works in 0.14.5, not in 0.15.1

```
ERROR in ./~/css-loader!./~/less-loader!./styles/bootstrap.custom.less
Module build failed: Error: Unable to parse color from string "rgba(255,255,255,0.15 25%)"
    at Object.Color (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\color\index.js:31:15)
    at Color (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\color\index.js:7:41)
    at colormin (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\colormin\index.js:20:17)
    at Array.map (native)
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:12:34
    at Array.map (native)
    at eachVal (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:11:31)
    at Array.map (native)
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:21:52
    at evalFunctionCall (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\reduce-function-call\index.js:73:10)
 @ ./styles/bootstrap.custom.less 4:14-127

ERROR in ./~/css-loader!./~/less-loader!./styles/vendor/kendo/web/kendo.common.less
Module build failed: Error: Unable to parse color from string "rgba(0,0,0,0 0)"
    at Object.Color (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\color\index.js:31:15)
    at Color (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\color\index.js:7:41)
    at colormin (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\colormin\index.js:20:17)
    at Array.map (native)
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:12:34
    at Array.map (native)
    at eachVal (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:11:31)
    at Array.map (native)
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:21:52
    at evalFunctionCall (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\reduce-function-call\index.js:73:10)
 @ ./styles/vendor/kendo/web/kendo.common.less 4:14-141

ERROR in ./~/css-loader!./~/less-loader!./styles/app.theme.black.less
Module build failed: Error: Unable to parse color from string "rgba(255,255,255,.12 0%)"
    at Object.Color (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\color\index.js:31:15)
    at Color (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\color\index.js:7:41)
    at colormin (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\colormin\index.js:20:17)
    at Array.map (native)
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:12:34
    at Array.map (native)
    at eachVal (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:11:31)
    at Array.map (native)
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:21:52
    at evalFunctionCall (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\reduce-function-call\index.js:73:10)
 @ ./~/style-loader/useable.js!./~/css-loader!./~/less-loader!./styles/app.theme.black.less 3:14-126

ERROR in ./~/css-loader!./~/less-loader!./styles/app.theme.blueopal.less
Module build failed: Error: Unable to parse color from string "rgba(255,255,255,.45 0%)"
    at Object.Color (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\color\index.js:31:15)
    at Color (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\color\index.js:7:41)
    at colormin (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\colormin\index.js:20:17)
    at Array.map (native)
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:12:34
    at Array.map (native)
    at eachVal (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:11:31)
    at Array.map (native)
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:21:52
    at evalFunctionCall (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\reduce-function-call\index.js:73:10)
 @ ./~/style-loader/useable.js!./~/css-loader!./~/less-loader!./styles/app.theme.blueopal.less 3:14-129

ERROR in ./~/css-loader!./~/less-loader!./styles/app.theme.bootstrap.less
Module build failed: Error: Unable to parse color from string "rgba(0,0,0,0.075 inset)"
    at Object.Color (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\color\index.js:31:15)
    at Color (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\color\index.js:7:41)
    at colormin (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\colormin\index.js:20:17)
    at Array.map (native)
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:12:34
    at Array.map (native)
    at eachVal (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:11:31)
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:19:26
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\postcss\lib\container.js:126:34
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\postcss\lib\container.js:104:26
 @ ./~/style-loader/useable.js!./~/css-loader!./~/less-loader!./styles/app.theme.bootstrap.less 3:14-130

ERROR in ./~/css-loader!./~/less-loader!./styles/app.theme.default.less
Module build failed: Error: Unable to parse color from string "rgba(255,255,255,.6 0%)"
    at Object.Color (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\color\index.js:31:15)
    at Color (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\color\index.js:7:41)
    at colormin (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\colormin\index.js:20:17)
    at Array.map (native)
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:12:34
    at Array.map (native)
    at eachVal (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:11:31)
    at Array.map (native)
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:21:52
    at evalFunctionCall (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\reduce-function-call\index.js:73:10)
 @ ./~/style-loader/useable.js!./~/css-loader!./~/less-loader!./styles/app.theme.default.less 3:14-128

ERROR in ./~/css-loader!./~/less-loader!./styles/app.theme.material.less
Module build failed: Error: Unable to parse color from string "rgba(0,0,0,0.075 inset)"
    at Object.Color (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\color\index.js:31:15)
    at Color (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\color\index.js:7:41)
    at colormin (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\colormin\index.js:20:17)
    at Array.map (native)
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:12:34
    at Array.map (native)
    at eachVal (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:11:31)
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:19:26
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\postcss\lib\container.js:126:34
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\postcss\lib\container.js:104:26
 @ ./~/style-loader/useable.js!./~/css-loader!./~/less-loader!./styles/app.theme.material.less 3:14-129

ERROR in ./~/css-loader!./~/less-loader!./styles/app.theme.materialblack.less
Module build failed: Error: Unable to parse color from string "rgba(0,0,0,0.075 inset)"
    at Object.Color (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\color\index.js:31:15)
    at Color (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\color\index.js:7:41)
    at colormin (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\colormin\index.js:20:17)
    at Array.map (native)
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:12:34
    at Array.map (native)
    at eachVal (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:11:31)
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:19:26
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\postcss\lib\container.js:126:34
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\postcss\lib\container.js:104:26
 @ ./~/style-loader/useable.js!./~/css-loader!./~/less-loader!./styles/app.theme.materialblack.less 3:14-134

ERROR in ./~/css-loader!./~/less-loader!./styles/app.theme.silver.less
Module build failed: Error: Unable to parse color from string "rgba(255,255,255,.45 0%)"
    at Object.Color (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\color\index.js:31:15)
    at Color (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\color\index.js:7:41)
    at colormin (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\colormin\index.js:20:17)
    at Array.map (native)
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:12:34
    at Array.map (native)
    at eachVal (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:11:31)
    at Array.map (native)
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:21:52
    at evalFunctionCall (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\reduce-function-call\index.js:73:10)
 @ ./~/style-loader/useable.js!./~/css-loader!./~/less-loader!./styles/app.theme.silver.less 3:14-127

ERROR in ./~/css-loader!./~/less-loader!./styles/app.theme.uniform.less
Module build failed: Error: Unable to parse color from string "rgba(0,0,0,.01 0%)"
    at Object.Color (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\color\index.js:31:15)
    at Color (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\color\index.js:7:41)
    at colormin (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\colormin\index.js:20:17)
    at Array.map (native)
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:12:34
    at Array.map (native)
    at eachVal (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:11:31)
    at Array.map (native)
    at C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\index.js:21:52
    at evalFunctionCall (C:\Users\Jacques-Louis\Creative Cloud Files\Memba\Memba.Blog\node_modules\css-loader\node_modules\cssnano\node_modules\postcss-colormin\node_modules\reduce-function-call\index.js:73:10)
 @ ./~/style-loader/useable.js!./~/css-loader!./~/less-loader!./styles/app.theme.uniform.less 3:14-128
Warning: Task "webpack:build" failed. Use --force to continue.
```

**Comment by markdalgleish** [comment]
Fixed in https://github.com/css-modules/css-selector-tokenizer/commit/5c8584009766eea9d03f8b3d676ece2d93ac06de.
